In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence
# fix random seed for reproducibility
tf.random.set_seed(7)

In [2]:
# load the dataset but only keep the top n words, zero the rest
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)

17473536/17464789 [==============================] - 0s 0us/step


In [3]:

# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [4]:

# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 32)           160000    
                                                                 
 lstm (LSTM)                 (None, 100)               53200     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/3
391/391 [==============================] - 289s 733ms/step - loss: 0.4316 - accuracy: 0.7884 - val_loss: 0.2970 - val_accuracy: 0.8761
Epoch 2/3
391/391 [==============================] - 287s 735ms/step - loss: 0.2653 - accuracy: 0.8937 - val_loss: 0.3236 - val_accuracy: 0.8748
Epoch 3/3
391/391 [

In [5]:

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 86.72%


In [11]:
y_pred = model.predict(X_test)

In [12]:
y_pred

array([[0.05080476],
       [0.9761088 ],
       [0.8479164 ],
       ...,
       [0.03951186],
       [0.45905858],
       [0.9525779 ]], dtype=float32)

In [6]:
X_train.shape

(25000, 500)

In [7]:
y_train.shape

(25000,)

In [8]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [9]:
y_train.dtype

dtype('int64')

In [10]:
y_test

array([0, 1, 1, ..., 0, 0, 0])