# **Machine Learning Tutorial Python 3: Linear Regression Multiple Variable**

In [1]:
#Step1: Import libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#Step2: Load data on collab
from google.colab import files
uploaded = files.upload()

Saving 3_houseprices.csv to 3_houseprices.csv


In [3]:
#step3: read dataframe with pandas
df = pd.read_csv('3_houseprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
#step4: correcting NaN value by taking the medium of other rows with code df.bedrooms.median()
#if you want to convert to integer whole number, use below code
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [6]:
#step5: fill the median number into NaN value
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
#fit model is used to train the model
# df[['area', 'bedrooms', 'age']]: create dataframe from existing dataframe with independent variables area, bedrooms, age
# df.price = target variable
reg= linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

383724.99999999994

In [12]:
reg.predict([[3000,3,40]])

array([444400.])

In [14]:
#checking the above price
137.25 * 3000 + (-26025) * 3 + (-6825) * 40 +383724.99999999994

444399.99999999994

In [15]:
reg.predict([[2500,4,5]])

array([588625.])