In [1]:
import numpy as np
import pandas as pd
import sys
import sklearn

import os

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Population and GDP by Country.csv to Population and GDP by Country.csv


In [3]:
df = pd.read_csv('Population and GDP by Country.csv', index_col='Country Name')
df.head()

GDP (current US$) Thousand   \
Country Name                                 
China                          11233000000   
India                           2295000000   
Indonesia                        932000000   
Korea, Rep.                     1500000000   
Saudi Arabia                     645000000   

              GDP per capita (current US$) Thousands  \
Country Name                                           
China                                            8.1   
India                                            1.7   
Indonesia                                        3.6   
Korea, Rep.                                     29.3   
Saudi Arabia                                    19.9   

               Population, total thousand   GDP per capita growth (annual %)   
Country Name                                                                   
China                              1387800                               6.24  
India                              1324500                               7.08  
Indonesia                           261600                               3.76  
Korea, Rep.                          51200                               2.54  
Saudi Arabia                         32400                              -0.60

In [4]:
df = df.apply(pd.to_numeric)

In [5]:
X=df.to_numpy()
X

array([[ 1.1233e+10,  8.1000e+00,  1.3878e+06,  6.2400e+00],
       [ 2.2950e+09,  1.7000e+00,  1.3245e+06,  7.0800e+00],
       [ 9.3200e+08,  3.6000e+00,  2.6160e+05,  3.7600e+00],
       [ 1.5000e+09,  2.9300e+01,  5.1200e+04,  2.5400e+00],
       [ 6.4500e+08,  1.9900e+01,  3.2400e+04, -6.0000e-01],
       [ 8.7000e+08,  1.0900e+01,  7.9800e+04,  1.6400e+00],
       [ 2.7230e+09,  4.1500e+01,  6.5600e+04,  1.4900e+00],
       [ 1.8695e+10,  5.7900e+01,  3.2310e+05,  9.3000e-01],
       [ 1.1000e+07,  2.7200e+01,  4.0000e+02, -3.6100e+00],
       [ 3.1900e+08,  3.7300e+01,  8.5000e+03,  2.4300e+00],
       [ 1.0900e+08,  2.7700e+01,  4.0000e+03, -2.3000e-01],
       [ 7.5000e+07,  1.6800e+01,  4.5000e+03,  8.0000e-02],
       [ 1.5200e+08,  5.7200e+01,  2.7000e+03, -3.8000e-01],
       [ 3.1900e+08,  5.6900e+01,  5.6000e+03,  2.2300e+00],
       [ 3.5700e+08,  3.8100e+01,  9.4000e+03,  1.9100e+00],
       [ 1.8000e+07,  5.0000e-01,  3.5400e+04, -5.4000e-01],
       [ 2.4960e+09,  6.

In [6]:
# calculated mean vector  
X_centered= X-X.mean(axis=0)
print(X_centered)

[[ 8.01638889e+09 -1.02972222e+01  1.09165833e+06  3.92611111e+00]
 [-9.21611111e+08 -1.66972222e+01  1.02835833e+06  4.76611111e+00]
 [-2.28461111e+09 -1.47972222e+01 -3.45416667e+04  1.44611111e+00]
 [-1.71661111e+09  1.09027778e+01 -2.44941667e+05  2.26111111e-01]
 [-2.57161111e+09  1.50277778e+00 -2.63741667e+05 -2.91388889e+00]
 [-2.34661111e+09 -7.49722222e+00 -2.16341667e+05 -6.73888889e-01]
 [-4.93611111e+08  2.31027778e+01 -2.30541667e+05 -8.23888889e-01]
 [ 1.54783889e+10  3.95027778e+01  2.69583333e+04 -1.38388889e+00]
 [-3.20561111e+09  8.80277778e+00 -2.95741667e+05 -5.92388889e+00]
 [-2.89761111e+09  1.89027778e+01 -2.87641667e+05  1.16111111e-01]
 [-3.10761111e+09  9.30277778e+00 -2.92141667e+05 -2.54388889e+00]
 [-3.14161111e+09 -1.59722222e+00 -2.91641667e+05 -2.23388889e+00]
 [-3.06461111e+09  3.88027778e+01 -2.93441667e+05 -2.69388889e+00]
 [-2.89761111e+09  3.85027778e+01 -2.90541667e+05 -8.38888889e-02]
 [-2.85961111e+09  1.97027778e+01 -2.86741667e+05 -4.03888889e

In [7]:
# Perform SVD
U, s, Vt = np.linalg.svd(X_centered)

print(f' shape of U = {U.shape}')
print(f' shape of s = {s.shape}')
print(f' shape of Vt = {Vt.shape}')

# create a cov matrix S from s
m, n = X.shape
S = np.zeros(X_centered.shape)
S[:n, :n] = np.diag(s)

print(f' shape of S = {S.shape}')

 shape of U = (36, 36)
 shape of s = (4,)
 shape of Vt = (4, 4)
 shape of S = (36, 4)


In [9]:
# for confirmation

u1 = U[:, 0]
u2 = U[:, 1]
u3 = U[:, 2]
u4 = U[:, 3]

v1 = Vt.T[:, 0]
v2 = Vt.T[:, 1]
v3 = Vt.T[:, 2]
v4 = Vt.T[:, 3]

print(f'X_centered = {X_centered.shape}')
print('\n=======')
print(f'U.shape = {U.shape}')
print(f's.shape = {s.shape}')
print(f'Vt.shape = {Vt.shape}')

print('\n=======')

print('left singular matrix U')
print('first (u1) to fourth vector (u4) of U')
print(f'u1  = {u1}')
print(f'u2  = {u2}')
print(f'u3  = {u3}')
print(f'u4  = {u4}')

print('\n=======')
print(f's = {s}' )
print(f'S (first 10 rows) = \n {S[:10]}')

print('\n=======')
print('right singular matrix V')
print('first (v1) to fourth vector (v4); they are in horizontal direction')
print(f'v1  = {v1}')
print(f'v2  = {v2}')
print(f'v3  = {v3}')
print(f'v4  = {v4}')

X_centered = (36, 4)

U.shape = (36, 36)
s.shape = (4,)
Vt.shape = (4, 4)

left singular matrix U
first (u1) to fourth vector (u4) of U
u1  = [-0.20745743  0.02385052  0.05912382  0.04442446  0.06655114  0.06072833
  0.01277424 -0.40056774  0.08295853  0.07498775  0.08042237  0.08130226
  0.07930957  0.07498775  0.07400434  0.08277738  0.01864881  0.07638522
 -0.50607708  0.07465132 -0.44608918  0.07139054  0.07892138  0.08220803
  0.08192336  0.07545357  0.00123214  0.07511714  0.07498775  0.07485835
  0.00547632  0.08112111  0.07255511  0.08241507  0.07493599 -0.44029225]
u2  = [ 0.26366709  0.41967798  0.03271655 -0.06081973 -0.05086619 -0.03692958
 -0.07992898 -0.30240887 -0.05052836 -0.05359622 -0.05110565 -0.05022329
 -0.05248195 -0.05472718 -0.05401347 -0.03702034  0.0566317   0.00579849
  0.38913508 -0.02035918 -0.10873592 -0.02867829 -0.03956465 -0.04752677
 -0.04888011 -0.04457461  0.05456946  0.02259126 -0.01646949 -0.03509494
  0.57953115 -0.04385203 -0.0319024  -0.05056293

Perform PCA on X

In [13]:
from sklearn.decomposition import PCA
pca4 = PCA(n_components=4)
X4D = pca4.fit_transform(X_centered)
COV_pca = pca4.get_covariance()
print(f' variance-covariance matrix calculated by sklearn :\n {COV_pca}')
print('\n this is the same with the above')

 variance-covariance matrix calculated by sklearn :
 [[ 4.26610488e+19  3.38366817e+10  2.21152819e+15  8.32894413e+08]
 [ 3.38366817e+10  3.46115135e+02 -2.29215131e+06 -2.02488175e+01]
 [ 2.21152819e+15 -2.29215131e+06  3.02503752e+11  6.31688148e+05]
 [ 8.32894413e+08 -2.02488175e+01  6.31688148e+05  8.53529302e+00]]

 this is the same with the above


Calculation of unitary matrix Upca where each column is eigenvector of Xc (by PCA)

In [14]:
# eigen vectors; u1, u2, u3, u4
U_pca=pca4.components_
print(f'eigenvector U_pca (in horizontal direction; U^T)= \n {U_pca}')

# as for comparison 
print('\n right singular matrix V by SVD')
print('first (v1) to fourth vector (v4); they are in horizontal direction')
print(f'v1  = {v1}')
print(f'v2  = {v2}')
print(f'v3  = {v3}')
print(f'v4  = {v4}')

eigenvector U_pca (in horizontal direction; U^T)= 
 [[ 9.99999999e-01  7.93151656e-10  5.18395177e-05  1.95235341e-11]
 [-5.18395177e-05 -2.15386238e-05  9.99999998e-01  3.13272553e-06]
 [-1.91364215e-09  9.99335548e-01  2.16384942e-05 -3.64480761e-02]
 [ 7.31754930e-11  3.64480761e-02 -2.34560258e-06  9.99335548e-01]]

 right singular matrix V by SVD
first (v1) to fourth vector (v4); they are in horizontal direction
v1  = [-9.99999999e-01 -7.93151656e-10 -5.18395177e-05 -1.95235341e-11]
v2  = [-5.18395177e-05 -2.15386238e-05  9.99999998e-01  3.13272553e-06]
v3  = [ 1.91364215e-09 -9.99335548e-01 -2.16384942e-05  3.64480761e-02]
v4  = [-7.31754930e-11 -3.64480761e-02  2.34560258e-06 -9.99335548e-01]


Confirm they are the same 

In [15]:
# eigenvalues - you will find the same.
eigenvalues = pca4.explained_variance_
print(f'PCA; eigenvalues of cov(X) = {eigenvalues}')

print(f'SVD: singular values of X = {s}')


print(f'\n  (singular value)^2 / (N-1)= \n  {s*s/(m-1)}')

PCA; eigenvalues of cov(X) = [4.26610489e+19 1.87859197e+11 2.32427622e+02 6.37508533e+00]
SVD: singular values of X = [3.86411272e+10 2.56419030e+06 9.01940507e+01 1.49374692e+01]

  (singular value)^2 / (N-1)= 
  [4.26610489e+19 1.87859197e+11 2.32427622e+02 6.37508533e+00]
