In [1]:
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install pandas-ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
data = yf.download(tickers ='EURUSD=X')
data.tail()

[*********************100%***********************]  1 of 1 completed


Open      High       Low     Close  Adj Close  Volume
Date                                                                 
2022-11-03  0.981441  0.983961  0.973122  0.981441   0.981441       0
2022-11-04  0.974963  0.993818  0.974849  0.974963   0.974963       0
2022-11-07  0.992881  1.000500  0.991945  0.992881   0.992881       0
2022-11-08  1.001863  1.009418  0.997606  1.001863   1.001863       0
2022-11-09  1.007658  1.009082  1.005935  1.007557   1.007557       0

# Adding Technical Indiators 

In [4]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['SMA']= ta.sma(data.Close, length=10)
data['EMA']= ta.ema(data.Close, length= 10)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)
#data['Price Diff ratio'] = data['Adj Close']/data['Adj Close'].shift()
# macd = data.ta.macd(fast =12, slow =26, signal =9)
# BB = data.ta.bbands(length=12, std =2)
# ADX = data.ta.adx(length = 20)
# ROC = data.ta.roc(length = 12)
# stochastic = data.ta.stochrsi(length= 14, rsi_length= 3, k=3)
# ST = data.ta.supertrend()
# SAR = data.ta.psar()
# OBV = data.ta.obv()
# Fib = data.ta.fwma(length= 15)
# Pivot = data.ta.
#cycle = data.ta.strategy()
momentum = data.ta.strategy('Momentum')
overlap = data.ta.strategy('overlap', length =20)
performance = data.ta.strategy('performance')
statistic = data.ta.strategy('statistic')
trend = data.ta.strategy('trend')
volatility = data.ta.strategy('volatility')
data = pd.concat([data, momentum, overlap, performance, statistic, trend, volatility], axis = 1)

39it [00:03, 12.75it/s]
32it [00:07,  4.47it/s]
2it [00:00,  6.38it/s]

[X] Not an available strategy.



14it [00:02,  5.26it/s]
14it [00:00, 17.97it/s]


In [5]:
data['Target'] = data['Adj Close']- data['Adj Close'].shift()
#data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

#data['TargetNextClose'] = data['Adj Close'].shift(-1)

#data.dropna(inplace=True)
#data.set_index(pd.DatetimeIndex(data[" Date"]), inplace=True)
#data.reset_index(inplace = True)
data.drop(['Volume'], axis=1, inplace=True)

In [6]:
#dropping unused indicators
data.drop(['PVO_12_26_9', 'PVOh_12_26_9', 'PVOs_12_26_9', 'QQEl_14_5_4.236', 'QQEs_14_5_4.236', 
           'SQZ_ON', 'SQZ_OFF', 'SQZ_NO', 'SQZPRO_ON_WIDE', 'SQZPRO_ON_NORMAL', 'SQZPRO_ON_NARROW', 
           'SQZPRO_OFF', 'SQZPRO_NO', 'HILOl_13_21', 'HILOs_13_21', 'SUPERTd_20_3.0', 'SUPERTl_20_3.0', 
           'SUPERTs_20_3.0', 'VWAP_D', 'VWMA_20', 'AMATe_LR_8_21_2', 'AMATe_SR_8_21_2', 
           'DEC_1', 'INC_1', 'PSARl_0.02_0.2', 'PSARs_0.02_0.2', 'PSARr_0.02_0.2', 'TTM_TRND_6', 
           'THERMOl_20_2_0.5', 'THERMOs_20_2_0.5'], axis=1, inplace=True)

In [7]:
#dropping N/A values
data.dropna(inplace=True)

In [8]:
data_set = data.iloc[:, ]#.values
pd.set_option('display.max_columns', None)

data_set.head(5)
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))
#data_set.to_csv('EURUSDTA.csv')

Open      High       Low     Close  Adj Close        RSI  \
Date                                                                       
2004-06-25  1.217093  1.220301  1.211299  1.220301   1.220301  54.911255   
2004-06-28  1.217493  1.222703  1.212797  1.218695   1.218695  53.966191   
2004-06-29  1.218695  1.219096  1.207496  1.209804   1.209804  48.968246   
2004-06-30  1.209497  1.220301  1.206797  1.218398   1.218398  53.434557   
2004-07-01  1.218294  1.220807  1.213902  1.216205   1.216205  52.185715   

                 SMA       EMA      EMAF      EMAM      EMAS   AO_5_34  \
Date                                                                     
2004-06-25  1.211252  1.213470  1.212295  1.219270  1.228477  0.003915   
2004-06-28  1.212501  1.214420  1.212905  1.219258  1.228347  0.004214   
2004-06-29  1.211821  1.213581  1.212610  1.219071  1.228101  0.004138   
2004-06-30  1.213591  1.214457  1.213161  1.219058  1.227973  0.003392   
2004-07-01  1.214872  1.214775  1.213451  1.219001  1.227817  0.003526   

            APO_12_26  BIAS_SMA_26       BOP       AR_26       BR_26  \
Date                                                                   
2004-06-25  -0.004064     0.004798  0.356376  110.146723  104.080689   
2004-06-28  -0.004026     0.002970  0.121319  102.676396   93.174030   
2004-06-29  -0.003715    -0.004658 -0.766428   97.844167   92.043138   
2004-06-30  -0.003018     0.002149  0.659116   95.391882   89.500287   
2004-07-01  -0.003248     0.000183 -0.302520   92.538520   86.754983   

            CCI_14_0.015     CFO_9     CG_10     CMO_14  COPC_11_14_10  \
Date                                                                     
2004-06-25     96.687193  0.296695 -5.491887  10.429627      -1.459795   
2004-06-28    139.668693 -0.135406 -5.491424   8.372822      -1.007222   
2004-06-29     35.320640 -0.592830 -5.490559  -2.456580      -0.611503   
2004-06-30     77.076490  0.127239 -5.493175   7.196892      -0.224307   
2004-07-01    100.411485 -0.094879 -5.496829   4.491116       0.391721   

              CTI_12     ER_10  BULLP_13  BEARP_13  FISHERT_9_1  FISHERTs_9_1  \
Date                                                                            
2004-06-25  0.565378  0.301160  0.007182 -0.001820     1.050317      0.553857   
2004-06-28  0.708947  0.210618  0.008788 -0.001118     1.532740      1.050317   
2004-06-29  0.504087  0.117624  0.005768 -0.005832     1.514270      1.532740   
2004-06-30  0.505436  0.350548  0.006249 -0.007256     1.321712      1.514270   
2004-07-01  0.686110  0.256192  0.006448 -0.000458     1.416469      1.321712   

            INERTIA_20_14      K_9_3      D_9_3       J_9_3  \
Date                                                          
2004-06-25      54.080546  77.773866  61.014173  111.293251   
2004-06-28      52.577876  79.816041  67.281462  104.885198   
2004-06-29      50.975851  69.274872  67.945932   71.932752   
2004-06-30      49.778713  73.752642  69.881502   81.494922   
2004-07-01      48.293417  70.535330  70.099445   71.407101   

            KST_10_15_20_30_10_10_10_15       KSTs_9  MACD_12_26_9  \
Date                                                                 
2004-06-25                   565.855172  1081.242549      0.001650   
2004-06-28                   476.873913   933.800855      0.001964   
2004-06-29                   308.814004   788.701893      0.001478   
2004-06-30                   367.119506   676.496573      0.001766   
2004-07-01                   419.951625   588.841234      0.001797   

            MACDh_12_26_9  MACDs_12_26_9    MOM_10    PGO_14  PPO_12_26_9  \
Date                                                                        
2004-06-25       0.000118       0.001532  0.018797  0.787240    -0.334645   
2004-06-28       0.000346       0.001618  0.012495  0.697344    -0.331337   
2004-06-29      -0.000112       0.001590 -0.006800 -0.099285    -0.305656   
2004-06-30       0.000141       0.001625  0.017701  0.

In [9]:
data.shape

(4739, 153)

# Scalling dataset

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)
print(data_set_scaled[0].size)

[[0.40320654 0.39837853 0.75166507 ... 0.1456964  0.48197543 1.        ]
 [0.40383305 0.40215665 0.7526544  ... 0.14535056 0.47123577 0.        ]
 [0.405715   0.39648337 0.74915408 ... 0.13767268 0.45386353 0.        ]
 ...
 [0.03654507 0.02829869 0.59471989 ... 0.25202206 0.50401568 1.        ]
 [0.03077161 0.02739873 0.59587987 ... 0.25776313 0.46627392 0.        ]
 [0.03693859 0.04876918 0.59938511 ... 0.25954601 0.48445841 1.        ]]
153


# Setting X and Y (label) dataset. Y= TargetClass column

In [11]:
X, Y = data_set_scaled[:, 0:151], data_set_scaled[:, -1] #dropping Y +Target column from X

# Splitting X-Y Train-Test sets

In [12]:
splitlimit = int(len(X)*0.8)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
Y_train, Y_test = Y[:splitlimit], Y[splitlimit:]

3791


In [24]:
# #change X dataframe to numpy array matrix
# X_train=X_train.to_numpy()
# X_test= X_test.to_numpy()

AttributeError: ignored

In [14]:
# #change Y dataframe to numpy array matrix
# Y_train=Y_train.to_numpy()
# Y_test= Y_test.to_numpy()

# PCA on X_train dataset

In [13]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

X_train_mean = X_train.mean(axis=0)
X_train_std = X_train.std(axis=0)

X_train = (X_train-X_train_mean)/X_train_std
x_train_PCA = pca.fit_transform(X_train)

In [44]:
# VP= pca.explained_variance_ratio_ * 100
# print("Variances (Percentage):")
# print(VP)

Variances (Percentage):
[4.16891614e+01 2.46231324e+01 6.47723560e+00 4.37900251e+00
 3.38544633e+00 1.88779032e+00 1.84907229e+00 1.64637339e+00
 1.49319051e+00 1.02729364e+00 8.94019940e-01 8.53024921e-01
 8.07426669e-01 7.44075421e-01 6.35691850e-01 5.97370025e-01
 5.58671925e-01 5.26820224e-01 4.76338099e-01 4.49918283e-01
 3.96533470e-01 3.75717204e-01 3.54724165e-01 3.10597074e-01
 3.00013684e-01 2.75360453e-01 2.59238333e-01 2.51510300e-01
 2.01759833e-01 1.88641522e-01 1.76300691e-01 1.41474676e-01
 1.38665341e-01 1.35686995e-01 1.26437960e-01 1.12347629e-01
 1.05407497e-01 9.74145318e-02 9.37519475e-02 7.71361574e-02
 7.23114625e-02 6.74559235e-02 6.48923662e-02 5.69534976e-02
 5.27019227e-02 4.73011831e-02 4.46448252e-02 4.14574227e-02
 3.93620416e-02 3.84647479e-02 3.21236958e-02 3.10165898e-02
 2.82495780e-02 2.71694194e-02 2.49001062e-02 2.04670785e-02
 1.77697396e-02 1.64809212e-02 1.46364825e-02 1.45591988e-02
 1.25334612e-02 1.17445334e-02 1.02261573e-02 9.57420542e-03


In [14]:
x_train_PCA[0].size

3

# Preparing training data for LSTM



In [15]:
# multiple feature from data provided to the model
Xi_train = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 14
#print(data_set_scaled.shape[0])
for j in range(3):#data_set_scaled[0].size, excluding Y
    Xi_train.append([])
    for i in range(backcandles, x_train_PCA.shape[0]):#backcandles+2
        Xi_train[j].append(x_train_PCA[i-backcandles:i, j])

In [16]:
#move axis from 0 to position 2
Xi_train=np.moveaxis(Xi_train, [0], [2])

In [17]:
#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
x_train =np.array(Xi_train)
yi_train=np.reshape(Y_train,(len(Y_train),1))
Yi_train = np.array(yi_train[backcandles:, 0])
y_train=np.reshape(Yi_train,(len(Yi_train),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

[[[ -4.06000003  -2.43802775   1.04111039]
  [ -4.00423321  -2.73870133   0.94639566]
  [ -4.25763063  -1.37527577  -0.80195823]
  ...
  [ -2.03523168  -8.87642183   1.11843736]
  [ -2.25719307  -7.20300087  -0.7732256 ]
  [ -2.09157628  -7.70074061  -0.04649602]]

 [[ -4.00423321  -2.73870133   0.94639566]
  [ -4.25763063  -1.37527577  -0.80195823]
  [ -3.9192872   -3.69556602   1.24528732]
  ...
  [ -2.25719307  -7.20300087  -0.7732256 ]
  [ -2.09157628  -7.70074061  -0.04649602]
  [ -2.24717836  -6.42490414  -1.45193336]]

 [[ -4.25763063  -1.37527577  -0.80195823]
  [ -3.9192872   -3.69556602   1.24528732]
  [ -3.91222746  -3.32823414   0.250245  ]
  ...
  [ -2.09157628  -7.70074061  -0.04649602]
  [ -2.24717836  -6.42490414  -1.45193336]
  [ -1.89205977  -7.81492952   0.30359226]]

 ...

 [[ -9.4456005    0.99208615  -3.29166054]
  [ -9.56869284   1.46129869  -3.38271949]
  [ -9.59815021   1.76525602  -2.58757236]
  ...
  [ -8.91648173  -2.31093205  -0.17923581]
  [ -9.2333101   -

# LSTM Model

In [18]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np

In [19]:
#tf.random.set_seed(20)
np.random.seed()

lstm_input = Input(shape=(backcandles, 3), name='lstm_input')
inputs = LSTM(150, name='first_layer')(lstm_input)
inputs = Dense(1, name='dense_layer')(inputs)
output = Activation('linear', name='output')(inputs)
model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss='mse')
model.fit(x=x_train, y=y_train, batch_size=15, epochs=20, shuffle=True, validation_split = 0.1)

Epoch 1/20
227/227 [==============================] - 8s 23ms/step - loss: 0.2943 - val_loss: 0.2610
Epoch 2/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2670 - val_loss: 0.2518
Epoch 3/20
227/227 [==============================] - 5s 21ms/step - loss: 0.2600 - val_loss: 0.2491
Epoch 4/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2568 - val_loss: 0.2611
Epoch 5/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2548 - val_loss: 0.2810
Epoch 6/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2522 - val_loss: 0.2520
Epoch 7/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2511 - val_loss: 0.2549
Epoch 8/20
227/227 [==============================] - 4s 20ms/step - loss: 0.2508 - val_loss: 0.2491
Epoch 9/20
227/227 [==============================] - 5s 20ms/step - loss: 0.2478 - val_loss: 0.2684
Epoch 10/20
227/227 [==============================] - 6s 26ms/step - loss: 0.2465 - val_lo

# Applying PCA on Test set

In [20]:
X_test_PCA = pca.transform(X_test)

In [21]:
X_test_PCA

array([[ 2.70811698e+00, -1.89148036e+00, -3.24236672e-01, ...,
         2.61850235e-04,  2.20009050e-03,  7.73220269e-04],
       [ 2.71474577e+00, -1.97412938e+00, -1.44529954e-01, ...,
         3.26522890e-04,  2.13551281e-03,  7.25748601e-04],
       [ 2.71900410e+00, -2.02655407e+00, -7.56829442e-02, ...,
         3.54345771e-04,  2.08746446e-03,  6.97899506e-04],
       ...,
       [ 8.51117981e-01, -2.27654989e+00,  3.67689683e-01, ...,
        -1.51226392e-03,  2.80839110e-03,  9.76106863e-04],
       [ 8.50262893e-01, -2.37463497e+00,  4.93886804e-01, ...,
        -1.63079779e-03,  2.79516191e-03,  9.71202228e-04],
       [ 9.10270472e-01, -2.70926282e+00,  7.05454927e-01, ...,
        -1.53234835e-03,  2.69559646e-03,  9.21820856e-04]])

# Transforming PCA test sets for prediction

In [22]:
Xi_test = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 14
#print(data_set_scaled.shape[0])
for j in range(151):#data_set_scaled[0].size, excluding Y
    Xi_test.append([])
    for i in range(backcandles, X_test_PCA.shape[0]):#backcandles+2
        Xi_test[j].append(X_test_PCA[i-backcandles:i, j])

In [23]:
#move axis from 0 to position 2
Xi_test=np.moveaxis(Xi_test, [0], [2])

In [24]:
x_test =np.array(Xi_test)
yi_test=np.reshape(Y_test,(len(Y_test),1))
Yi_test = np.array(yi_test[backcandles:, 0])
y_test=np.reshape(Yi_test,(len(Yi_test),1))

In [27]:
x_test.shape

(934, 14, 151)

# Model Predictions

In [29]:
y_pred = model.predict(x_test)
y_pred=np.where(y_pred > 0.41, 1,0)
for i in range(50):
    print(y_pred[i], y_test[i])

30/30 [==============================] - 0s 16ms/step
[0] [0.]
[0] [1.]
[0] [0.]
[0] [1.]
[0] [1.]
[0] [1.]
[0] [1.]
[0] [0.]
[1] [1.]
[0] [1.]
[0] [1.]
[0] [1.]
[0] [0.]
[1] [0.]
[1] [1.]
[0] [0.]
[0] [0.]
[0] [0.]
[0] [0.]
[1] [0.]
[1] [0.]
[1] [1.]
[0] [0.]
[1] [0.]
[1] [1.]
[0] [1.]
[0] [1.]
[0] [0.]
[1] [1.]
[1] [0.]
[1] [0.]
[1] [1.]
[0] [0.]
[1] [1.]
[1] [1.]
[0] [0.]
[0] [0.]
[1] [0.]
[1] [1.]
[1] [1.]
[0] [1.]
[0] [0.]
[1] [0.]
[1] [1.]
[1] [1.]
[0] [0.]
[0] [1.]
[1] [1.]
[1] [1.]
[1] [0.]


In [30]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score

In [31]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

MNB_f1 = round(f1_score(y_test, y_pred, average='weighted'), 3)
MNB_accuracy = round((accuracy_score(y_test, y_pred)*100),2)

print("Accuracy : " , MNB_accuracy , " %")
print("f1_score : " , MNB_f1)

              precision    recall  f1-score   support

         0.0       0.57      0.70      0.63       471
         1.0       0.60      0.46      0.53       463

    accuracy                           0.58       934
   macro avg       0.59      0.58      0.58       934
weighted avg       0.59      0.58      0.58       934

[[330 141]
 [248 215]]
Accuracy :  58.35  %
f1_score :  0.578
